Config = {}

-- DISCORD WEBHOOK --
Config.url = "YOUR WEBHOOK URL" -- PASTE YOUR WEBHOOK URL HERE TO ENABLE CHAT TO DISCORD --
Config.image = "YOUR WEBHOOK IMAGE URL" -- PASTE YOUR IMAGE URL IF YOU WANT IT TO BE DISPLAYED --
-- DISCORD WEBHOOK --

-- CUSTOM DATA --
Config.enablecustomdata = true
-- CUSTOM DATA --

-- PLEASE, DON'T TOUCH THIS, BCZ IT IS BROKEN -- !!
-- DISCORD RICH PRESENCE --
-- Config.discordid = ""       -- DISCORD ID -- 
-- Config.bigpicture = ""      -- WHAT IS PRESENTED ON THE RPC || YOU NEED TO UPLOAD AN IMAGE TO DISCORD DEV APP AND PASTE HERE THE NAME OF THE PICTURE -- 
-- Config.bigtext = ""         -- WHAT IS PRESENTED ON THE BIG PICTURE WHEN YOU HOVER ON IT--
-- Config.smallpicture = ""    -- WHAT IS PRESENTED ON THE SMALL RPC PICTURE -- || YOU NEED TO UPLOAD AN IMAGE TO DISCORD DEV APP AND PASTE HERE THE NAME OF THE PICTURE
-- Config.smalltext = ""       -- WHAT IS PRESENTED ON THE SMALL PICTURE WHEN YOU HOVER ON IT --
-- DISCORD RICH PRESENCE -- 



--/////////////////////////--
--   made by sync with <3   -- 
--/////////////////////////--